TASK_CREATED = 'Tarea creada exitosamente'
TASK_UPDATED = 'Tarea actualizada exitosamente'
TASK_DELETED = 'Tarea eliminada exitosamente'

#ImYwMmY2ZWU5YmVjNjBjMWRmYzM0Y2JjYTZiNjM4YTZmYTdlOTkxMDci.XuFuzg.NMB47wL4Cux8fXwcNdw5hLxX6hk
#ImYwMmY2ZWU5YmVjNjBjMWRmYzM0Y2JjYTZiNjM4YTZmYTdlOTkxMDci.XuFvWw.QvCMLvqpupxIPyJ1GLE2qhn2dJQ